export const words = [
  { text: "Welcome", className: "text-white font-bold " },
  { text: "to", className: " text-white" },
  { text: "THE", className: "text-[#FFD700]" },
  { text: "STUDENT", className: "text-[#FFD700] font-bold " },
  { text: "FORUM.", className: "text-[#FFD700] font-bold " },
];
export const events = [
  {
    title: "Event 1",
    description: "Exciting event about technology",
    rating: 3,
    price: 1,
    teamSize: 4,
  },
  {
    title: "Event 2",
    description: "A fun-filled music festival",
    rating: 5,
    price: 450,
    teamSize: 2,
  },
  {
    title: "Event 3",
    description: "Networking event for professionals",
    rating: 4,
    price: 320,
    teamSize: 1,
  },
  {
    title: "Event 4",
    description: "Outdoor adventure and hiking trip",
    rating: 2,
    price: 180,
    teamSize: 5,
  },
  {
    title: "Event 5",
    description: "Food festival with various cuisines",
    rating: 4,
    price: 390,
    teamSize: 3,
  },
  {
    title: "Event 6",
    description: "Art and craft workshop",
    rating: 5,
    price: 260,
    teamSize: 2,
  },
  {
    title: "Event 7",
    description: "Business seminar on entrepreneurship",
    rating: 3,
    price: 310,
    teamSize: 1,
  },
  {
    title: "Event 8",
    description: "Charity fundraiser for a good cause",
    rating: 4,
    price: 500,
    teamSize: 6,
  },
  {
    title: "Event 9",
    description: "Comedy night with famous stand-up artists",
    rating: 5,
    price: 420,
    teamSize: 2,
  },
  {
    title: "Event 10",
    description: "Technology expo showcasing new innovations",
    rating: 3,
    price: 290,
    teamSize: 3,
  },
  {
    title: "Event 11",
    description: "Book reading and author interaction",
    rating: 4,
    price: 260,
    teamSize: 1,
  },
  {
    title: "Event 12",
    description: "Gaming tournament for esports enthusiasts",
    rating: 5,
    price: 480,
    teamSize: 4,
  },
  {
    title: "Event 13",
    description: "Photography workshop with experts",
    rating: 4,
    price: 340,
    teamSize: 2,
  },
  {
    title: "Event 14",
    description: "Cultural dance and music performance",
    rating: 3,
    price: 200,
    teamSize: 5,
  },
  {
    title: "Event 15",
    description: "Science fair for students and researchers",
    rating: 5,
    price: 550,
    teamSize: 6,
  },
  {
    title: "Event 16",
    description: "Startup pitch event for investors",
    rating: 4,
    price: 400,
    teamSize: 3,
  },
  {
    title: "Event 17",
    description: "Coding bootcamp for developers",
    rating: 5,
    price: 450,
    teamSize: 1,
  },
  {
    title: "Event 18",
    description: "Yoga and wellness retreat",
    rating: 3,
    price: 220,
    teamSize: 2,
  },
  {
    title: "Event 19",
    description: "Astronomy night with telescope sessions",
    rating: 5,
    price: 380,
    teamSize: 4,
  },
  {
    title: "Event 20",
    description: "Fashion show featuring latest trends",
    rating: 4,
    price: 370,
    teamSize: 2,
  },
  {
    title: "Event 21",
    description: "Live theater drama performance",
    rating: 3,
    price: 260,
    teamSize: 1,
  },
  {
    title: "Event 22",
    description: "Science fiction movie screening",
    rating: 5,
    price: 320,
    teamSize: 3,
  },
  {
    title: "Event 23",
    description: "History museum exhibition tour",
    rating: 4,
    price: 250,
    teamSize: 2,
  },
  {
    title: "Event 24",
    description: "Car and bike show featuring new models",
    rating: 5,
    price: 480,
    teamSize: 4,
  },
  {
    title: "Event 25",
    description: "Public speaking and storytelling workshop",
    rating: 3,
    price: 180,
    teamSize: 1,
  },
  {
    title: "Event 26",
    description: "DJ night with electronic dance music",
    rating: 4,
    price: 310,
    teamSize: 2,
  },
  {
    title: "Event 27",
    description: "Marathon for a social cause",
    rating: 5,
    price: 230,
    teamSize: 5,
  },
  {
    title: "Event 28",
    description: "Virtual reality gaming experience",
    rating: 4,
    price: 360,
    teamSize: 3,
  },
  {
    title: "Event 29",
    description: "Local farmers' market and organic fair",
    rating: 3,
    price: 190,
    teamSize: 2,
  },
  {
    title: "Event 30",
    description: "Business networking dinner",
    rating: 5,
    price: 500,
    teamSize: 1,
  },
  {
    title: "Event 31",
    description: "Wildlife photography expedition",
    rating: 4,
    price: 420,
    teamSize: 4,
  },
  {
    title: "Event 32",
    description: "Cooking competition with celebrity chefs",
    rating: 3,
    price: 290,
    teamSize: 3,
  },
  {
    title: "Event 33",
    description: "Cybersecurity awareness workshop",
    rating: 5,
    price: 460,
    teamSize: 2,
  },
  {
    title: "Event 34",
    description: "Artificial intelligence conference",
    rating: 4,
    price: 400,
    teamSize: 1,
  },
  {
    title: "Event 35",
    description: "Mindfulness meditation retreat",
    rating: 5,
    price: 280,
    teamSize: 2,
  },
  {
    title: "Event 36",
    description: "Karaoke night with friends",
    rating: 3,
    price: 210,
    teamSize: 4,
  },
  {
    title: "Event 37",
    description: "Cosplay competition and comic convention",
    rating: 5,
    price: 490,
    teamSize: 5,
  },
  {
    title: "Event 38",
    description: "Music composition and songwriting workshop",
    rating: 4,
    price: 350,
    teamSize: 2,
  },
  {
    title: "Event 39",
    description: "Street art festival and graffiti showcase",
    rating: 3,
    price: 200,
    teamSize: 3,
  },
  {
    title: "Event 40",
    description: "Tech startup hackathon",
    rating: 5,
    price: 420,
    teamSize: 6,
  },
  {
    title: "Event 41",
    description: "Beach cleanup drive for environmentalists",
    rating: 4,
    price: 150,
    teamSize: 2,
  },
  {
    title: "Event 42",
    description: "Historical city tour with guides",
    rating: 3,
    price: 270,
    teamSize: 1,
  },
  {
    title: "Event 43",
    description: "Dance battle competition",
    rating: 5,
    price: 390,
    teamSize: 4,
  },
  {
    title: "Event 44",
    description: "Board game night for strategy lovers",
    rating: 4,
    price: 180,
    teamSize: 2,
  },
  {
    title: "Event 45",
    description: "Manga and anime fan meetup",
    rating: 5,
    price: 260,
    teamSize: 3,
  },
  {
    title: "Event 46",
    description: "Retro video game tournament",
    rating: 3,
    price: 240,
    teamSize: 2,
  },
  {
    title: "Event 47",
    description: "E-commerce business strategy summit",
    rating: 5,
    price: 470,
    teamSize: 1,
  },
  {
    title: "Event 48",
    description: "DIY home decor and craft workshop",
    rating: 4,
    price: 210,
    teamSize: 2,
  },
  {
    title: "Event 49",
    description: "Virtual music concert with top artists",
    rating: 5,
    price: 500,
    teamSize: 6,
  },
  {
    title: "Event 50",
    description: "Space exploration and Mars colonization talk",
    rating: 4,
    price: 350,
    teamSize: 3,
  },
];

export const contingentPrice = 1;

export const contingentUpiLink = `upi://pay?pa=8296472301@axl&pn=MohammedMaaz&am=${contingentPrice}&cu=INR`;
